---

- import_tasks: 'setup_environment.yml'
- import_tasks: 'setup_profile.yml'

- name: Setup apt proxy
  import_tasks: 'setup_apt.yml'
  tags:
    - proxy
    - apt

- name: Setup git proxy
  import_tasks: 'setup_git.yml'
  tags:
    - proxy
    - git

- name: Setup yarn proxy
  import_tasks: 'setup_yarn.yml'
  tags:
    - proxy
    - yarn

- name: Setup docker proxy
  import_tasks: 'setup_docker.yml'
  tags:
    - proxy
    - docker
