---

- name: Set facts for environment proxy
  set_fact:
    env_proxy: []
    no_proxy: "{{ no_proxy | join(',') }}"

- name: Create the environment block
  set_fact:
    env_proxy: "{{ env_proxy }} + ['{{ item }}=http://{{ proxy.address }}:{{ proxy.port }}/']"
  with_items:
    - http_proxy
    - https_proxy
    - ftp_proxy
    - HTTP_PROXY
    - HTTPS_PROXY
    - FTP_PROXY

- name: Append to the environment block
  set_fact:
    env_proxy: "{{ env_proxy }} + ['{{ item }}={{ no_proxy }}']"
  with_items:
    - no_proxy
    - NO_PROXY

- name: Update /etc/environment
  blockinfile:
    dest: /etc/environment
    block: "{{ env_proxy | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROXY"
  become: true
