---
- name: Blank arrays
  set_fact:
    b1: []

- name: Set no_proxy
  set_fact:
    no_proxy: "{{ no_proxy | join(',') }}"

- name: Create the environment block
  set_fact:
    b1: "{{ b1 }} + ['{{ item }}=http://{{ proxy.address }}:{{ proxy.port }}/']"
  with_items:
    - http_proxy
    - https_proxy
    - ftp_proxy
    - HTTP_PROXY
    - HTTPS_PROXY
    - FTP_PROXY

- name: Append to the environment block
  set_fact:
    b1: "{{ b1 }} + ['{{ item }}={{ no_proxy }}']"
  with_items:
    - no_proxy
    - NO_PROXY

- debug:
    msg: "{{ b1 }}"

- name: Update /etc/environment
  blockinfile:
    dest: /etc/environment
    block: "{{ b1 | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROXY"
  become: true
