---

- name: Set facts for apt proxy
  set_fact:
    apt_proxy: []

- name: Create the apt.conf block
  set_fact:
    apt_proxy: "{{ apt_proxy }} + ['{{ item }};']"
  with_items:
    - Acquire::http::proxy "http://{{ proxy.address }}:{{ proxy.port }}/"
    - Acquire::ftp::proxy "ftp://{{ proxy.address }}:{{ proxy.port }}/"
    - Acquire::https::proxy "http://{{ proxy.address }}:{{ proxy.port }}/"

- name: Update /etc/apt/apt.conf.d/80proxy
  blockinfile:
    dest: /etc/apt/apt.conf.d/80proxy
    block: "{{ apt_proxy | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROXY"
    create: true
  become: true
